#==========================================================================
# Description: Build Armbian For rockchip boxes
# Copyright (C) 2021 https://github.com/ophub/rockchip-armbian
#==========================================================================

name: Use Releases file to build armbian

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      set_release:
        description: "Select OS Release."
        required: false
        default: "jammy"
        type: choice
        options:
          - jammy
      armbian_board:
        description: "Select rockchip Board."
        required: false
        default: "all"
        type: choice
        options:
          - all
          - rock5b
          - r66s
          - r68s
          - beikeyun
          - l1pro
      armbian_kernel:
        description: "Select kernel version."
        required: false
        default: "6.0.5"
        type: choice
        options:
          - 6.0.5
      auto_kernel:
        description: "Auto use the latest kernel."
        required: false
        default: true
        type: boolean
      armbian_size:
        description: "Set armbian rootfs size(Unit: MiB)."
        required: false
        default: "2560"
      armbian_fstype:
        description: "Select armbian rootfs type."
        required: false
        default: "ext4"
        type: choice
        options:
          - ext4
          - btrfs
      armbian_sign:
        description: "Set armbian custom name."
        required: false
        default: ""

env:
  TZ: America/New_York

jobs:
  build:
    runs-on: ubuntu-22.04
    if: ${{ github.event.repository.owner.id }} == ${{ github.event.sender.id }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Initialization environment
        id: init
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc 2>/dev/null
          sudo -E apt-get -qq update
          sudo -E apt-get -qq install -y $(curl -fsSL https://is.gd/depend_ubuntu2204_armbian)
          sudo -E apt-get -qq autoremove --purge
          sudo -E apt-get -qq clean
          sudo timedatectl set-timezone "${TZ}"
          echo "status=success" >> ${GITHUB_OUTPUT}

      - name: Download Armbian from Releases
        id: down
        if: ${{ steps.init.outputs.status }} == 'success' && !cancelled()
        run: |
          armbian_buildpath="build/output/images"
          [[ -d "${armbian_buildpath}" ]] || mkdir -p "${armbian_buildpath}"
          down_repo="https://api.github.com/repos/${GITHUB_REPOSITORY}/releases"
          down_path="Armbian_rockchip_${{ inputs.set_release }}.*/Armbian_.*-trunk_.*.img.gz"

          # down_filename: Armbian_rockchip_jammy_05.17.1924/Armbian_22.11.0-trunk_5.10.70.img.gz
          down_filename="$(curl -s "${down_repo}" | grep -oE "${down_path}" | head -n 1)"
          down_file="https://github.com/${GITHUB_REPOSITORY}/releases/download/${down_filename}"
          [[ -z "${down_file}" ]] && echo "Invalid download file." && exit 1
          wget -q -P "${armbian_buildpath}" "${down_file}" && sync
          cd "${armbian_buildpath}" && gzip -df *.img.gz && sync

          echo "ARMBIAN_RELEASE=${{ inputs.set_release }}" >> ${GITHUB_ENV}
          echo "status=success" >> ${GITHUB_OUTPUT}

      - name: Rebuild Armbian [ ${{ env.ARMBIAN_RELEASE }} ]
        uses: ophub/rockchip-armbian@main
        if: ${{ steps.down.outputs.status }} == 'success' && !cancelled()
        with:
          armbian_path: build/output/images/*.img
          armbian_board: ${{ inputs.armbian_board }}
          armbian_kernel: ${{ inputs.armbian_kernel }}
          auto_kernel: ${{ inputs.auto_kernel }}
          armbian_size: ${{ inputs.armbian_size }}
          armbian_fstype: ${{ inputs.armbian_fstype }}
          armbian_sign: ${{ inputs.armbian_sign }}

      - name: Upload Armbian image to Release
        uses: ncipollo/release-action@main
        if: ${{ env.PACKAGED_STATUS }} == 'success' && !cancelled()
        with:
          tag: Armbian_rockchip_${{ env.ARMBIAN_RELEASE }}_${{ env.PACKAGED_OUTPUTDATE }}
          artifacts: ${{ env.PACKAGED_OUTPUTPATH }}/*
          allowUpdates: true
          token: ${{ secrets.GH_TOKEN }}
          body: |
            This is Armbian image for rockchip boxes
            * Firmware information
            Default username: root
            Default password: 1234
            Update command: armbian-update
